### ISSUE TITLE
Help with rmega-up command

### ISSUE THREAD

**Issue by nyol** [topac/rmega#13]
Hello I would like to get some help
I never had contact Ruby, however I managed to install it in the 2.2.2 version on a VPS Centos 6.6 64bit.

The rmega-dl command worked perfectly.

However the rmega-up command returns me the following error:
Error: User email is required

Investigating a little more I noticed that one existed rmega_account.yml.example file.

I put my account details MEGA and rename it to rmega_account.yml.

Yet still get the error mentioned when I run rmega-up command

the I do to use only these two commands: download and upload files to the mega using ssh terminal?

**Comment by topac** [comment]
rmega_account.yml.example is for testing purpose. 

You should use rmega-up this way: `rmega-up FILE_TO_UPLOAD -u YOUR_EMAIL --pass`
