### ISSUE TITLE
link

### ISSUE THREAD

**Issue by steam7** [topac/rmega#17]
here you can see the folder
https://mega.nz/#F!eds3WDpb!imq91_iprHOmEvc7shWZ_Q

but here link is encrypted and can only be download with JDownloader
https://mega.nz/#N!CA8SCYzI!vf_VIlNK6mAfsvt-wCcn2SXCN-zeJEZ23z5ysGkqNuI=###n=eds3WDpb

you can easily solve to download it from the terminal?

**Comment by topac** [comment]
Hi, if I understood correctly the first link don't work (in fact i get ```ERROR: Access violation (e.g., trying to write to a read-only share)``` with ```rmega-dl``` (and this could be a bug). 

The second link you wrote is invalid. If I navigate to ```https://mega.nz/#N!CA8SCYzI!vf_VIlNK6mAfsvt-wCcn2SXCN-zeJEZ23z5ysGkqNuI=###n=eds3WDpb``` I get the MEGA login page.

Is that correct?

**Comment by topac** [comment]
Fixed with 12cc7e4e90e8e9ec5cfe16ed9cb4a06d33283900
