### ISSUE TITLE
ERROR: end of file reached, rmega-up command

### ISSUE THREAD

**Issue by nishiam27** [topac/rmega#25]
I tried to use the "rmega-up" command to upload a test file called "a.pdf."
However, rmega keeps throwing up the error, "ERROR: end of file reached"
Here is the exact code I used:
"**USER**$ rmega-up a.pdf -u **EMAIL_ID**@gmail.com --pass"
(I also tried "a.pdf" with the quotes, didn't make a difference)
It logs into the account, and shows an initial upload phase where it says, "[Upload] 0.0 bytes of 737.46 kb, 0.0% @ 0.0 bytes/s, 4 threads", but then just throws up the error, "ERROR: end of file reached"

Kindly help me

**Comment by topac** [comment]
Seems a bug or a change in the protocol. I'm going to debug it.

**Comment by topac** [comment]
fixed with version 0.2.4
