### ISSUE TITLE
Unable to allocate space for file

### ISSUE THREAD

**Issue by nixuxocuta** [topac/rmega#26]
Error when running rmega-dl even as root to download to external drive

[Allocate] 0.0 bytes of 8.71 GB, 0.0% @ 0.0 bytes/s, 4 threadsTraceback (most recent call last):
	9: from /usr/local/bin/rmega-dl:23:in `<main>'
	8: from /usr/local/bin/rmega-dl:23:in `load'
	7: from /var/lib/gems/2.5.0/gems/rmega-0.2.4/bin/rmega-dl:32:in `<top (required)>'
	6: from /var/lib/gems/2.5.0/gems/rmega-0.2.4/lib/rmega/cli.rb:113:in `cli_rescue'
	5: from /var/lib/gems/2.5.0/gems/rmega-0.2.4/bin/rmega-dl:65:in `block in <top (required)>'
	4: from /var/lib/gems/2.5.0/gems/rmega-0.2.4/bin/rmega-dl:65:in `each_with_index'
	3: from /var/lib/gems/2.5.0/gems/rmega-0.2.4/bin/rmega-dl:65:in `each'
	2: from /var/lib/gems/2.5.0/gems/rmega-0.2.4/bin/rmega-dl:68:in `block (2 levels) in <top (required)>'
	1: from /var/lib/gems/2.5.0/gems/rmega-0.2.4/lib/rmega/nodes/downloadable.rb:76:in `download'
/var/lib/gems/2.5.0/gems/rmega-0.2.4/lib/rmega/nodes/downloadable.rb:12:in `allocate': Unable to allocate space for file /media/ubuntu/hdd1/InstallESD.iso (RuntimeError)

**Comment by topac** [comment]
Hi @nixuxocuta, please check:
* if you have enough free space on your external drive (> 9GB)
* if you have read and write access on your external drive
* try downloading a smaller file (e.g. 1mb), is working in that case?
* check if your external drive filesystem support files bigger than 8GB (if the filesystem is FAT32 max filesize is 4GB)
