### ISSUE TITLE
Error Message when Quota of Plan Exceeded is "ERROR: Unexpected Length"

### ISSUE THREAD

**Issue by FSiffer-FHNW** [topac/rmega#27]
using rmega-dl.

I encountered "ERROR: Unexpected Length". I figured it eventually out (Free Quote Exceeded), but the error message does not really indicated anything useful to the user.

Moreover, I have a pretty sizeable collection of links which is being downloaded - but as soons as one of the links does not work (after the 10 retries) (with the above mentioned error), rmega-dl stops. But links later in the list work - so, imo it would be much more useful to message the user that the download has failed, _but then continue_ working on the rest of the list.

**Comment by topac** [comment]
Interesting. The free/pay quota is something added probably in the last year since i remember downloading a lot in the early days without any error. I'm going to clarify the error and dig a little bit more on this topic. Although is strange that your other links are downloaded without any problem, the server should block you based on your ip address for a certain amount of time 😕

**Comment by FSiffer** [comment]
true, their info page does say it blocks the ip - but it seems it does not... if you need links to test, i can send them to you directly by dm

**Comment by topac** [comment]
> true, their info page does say it blocks the ip - but it seems it does not... if you need links to test, i can send them to you directly by dm

yep that would be great, now that /r/megalinks is closed

**Comment by topac** [comment]
> and one more side note, i had to crawl the page where i got the links from using another tool and filter to mega links myself - rmega-dl could not do it

rmega does only a basic crawling of the html, is the links are constructed somehow with js they will be missed. But if you could provide the link I can check for bugs

**Comment by topac** [comment]
> encountered "ERROR: Unexpected Length".

If you call rmega-dl with ```--debug``` you should get the whole exception details

**Comment by FSiffer** [comment]
yeah, i saw that, --debug did not tell me much more though, I only figured the issue out when i opened the link on my own in the browser.

anyway, do you have some kind of email address of something for me to send you the link collection as well as the original site i crawled? I'd rather not share it here.

**Comment by topac** [comment]
> anyway, do you have some kind of email address of something for me to send you the link collection as well as the original site i crawled? I'd rather not share it here.

the email addr in rmega.gemspec

**Comment by topac** [comment]
fixed with ver. 0.2.5
