### ISSUE TITLE
Command issue

### ISSUE THREAD

**Issue by Psychurgy** [topac/rmega#28]
I manage to download files with "rmega-dl" but can't sign in and download them.

I get an error: `ERROR: undefined method `folders' for nil:NilClass`

I use the code:
rmega-dl 'https://mega.nz/#F!LS***' -o /downloads/Mega/  -u ***@163.com --pass ***

I get the code working without the signing in part.
Can't figure out whats wrong.

**Comment by topac** [comment]
Hi @Psychurgy, thanks for reporting this. The error you are getting is indeed misleading and it should be changed.
When you call `rmega-dl` with authentication (-u and --pass) the first arg of the command must be a path to a file that you have in your mega drive, for e.g.:

```
mega-dl /photos/pic1.jpg --user foobar@example.com --pass
```

recalling your example, rmega-dl is searching in your drive for a file named 'https://mega.nz/#F!LS***' that is missing. To download files for which a *sharing url* has been created call `rmega-dl` without authenticating, for e.g.:

```
rmega-dl 'https://mega.nz/#F!LS***'
```

**Comment by Psychurgy** [comment]
Thank you for the answer. I'm still learning and trying to figure out how different codes have been written.

Since I'm hitting the download cap without authentication. `ERROR: Transfer quota exceeded`

Is it possible to download straight from the source (outside my drive) since I have mega pro to raise the download limit? Or should I first just import stuff to my drive and download it from there?

**Comment by topac** [comment]
good point, sadly I don't have mega PRO now thus I'm unable to do a test here. I assume that if you import the file in your drive and then download it from there you should consume your PRO quota...
