### ISSUE TITLE
Link file handling

### ISSUE THREAD

**Issue by john-arvid** [topac/rmega#33]
A feature request. (I will look into it if I learn ruby quickly)

When having a list with links it would be nice that rmega tags completed links so it doesn't use them again, same with those that are dead. (Use again happens when a error occur and you don't know what link it was working with)
This could also be used when scraping websites, store in a file, tag those completed or faulty.

**Comment by topac** [comment]
this is beyond the scope of a simple downloader. This additional logic should be coded in a wrapper of mega-dl.
