### ISSUE TITLE
ERROR: Protocol error @ dir_s_mkdir 

### ISSUE THREAD

**Issue by john-arvid** [topac/rmega#36]
I get this error when there is a space and or a : in the directory name.
Using rmega-dl.

**Comment by john-arvid** [comment]
It looks like it is the :
Maybe have a fallback to change it to . instead? I see mega-sync does this (and maybe others).

**Comment by topac** [comment]
Thanks for finding this. What filesystem are you on? Can you share the whole error backtrace? Also try use the `--debug` flag when doing these tests

**Comment by john-arvid** [comment]
I don’t have the mega link so I can’t reproduce. Just wanted to inform. 
Fs: ext4
