### ISSUE TITLE
[Feature Request] HTTP connection reuse

### ISSUE THREAD

**Issue by baconwaifu** [topac/rmega#38]
Currently, for every call to `http_get_content()` a new connection is created. this is slow. *very* slow. 10Mbps on a 200Mbps network slow.

This also eliminates HTTP/2's throughput benefits for small requests (such as API requests interleaved with data)

A solution would be to modify Rmega::Net to a more object-oriented approach (or at least offer it) such that at least each file operates over a single connection. Possibly even going as far as one connection per host per thread.

**Comment by topac** [comment]
I've just took a look at this old code and it seems so.
As you suggest, the correct solution should be 1 connection kept-alive and per host per thread.

I'll ping you for a review of the new code soon :)

**Comment by baconwaifu** [comment]
Some testing says that there's nothing that breaks if using a per-thread connection pool (technically per-fiber, using `Thread.current`) but there is another issue stopping that from *doing* anything: Pool creates a new thread for every single chunk, rather than keeping threads alive for as long as possible.

Modifying Pool so that threads live until they run out of work, only creating new threads up to the limit seems to work fine. but that reveals another issue: there's no coherent place to call 'finish' for HTTP requests. It would require quite a bit more "upwards visibility" in the network stack, or an open/close interface in Net (what I'm about to try)

**Comment by baconwaifu** [comment]
tested adding an `http_wrap` method in Net, and wrapping the `each_chunk` in it. Opens a connection to the storage server even if one may not be needed, but it seems to work? it's at least re-using the HTTP objects. Another possible (albeit hacky) solution is to simply keep all `userstorage.mega.co.nz` connections open for the lifetime of the thread, and let the GC close them.

**Comment by baconwaifu** [comment]
Just tested a dirty workaround (let the GC close the userstorage connections for us), can confirm persistent connections make a *huge* difference in speed. it's now capable of hitting 100Mbps on 4 threads.

**Comment by topac** [comment]
checkout this new branch https://github.com/topac/rmega/tree/conn_pool

**Comment by topac** [comment]
@baconwaifu have you tried using the changes from the conn_pool branch?

**Comment by baconwaifu** [comment]
Was busy with schoolwork and car stuff. Will take a look later today.

**Comment by vijayanandnandam** [comment]
using Typhoeus instead of plain net/http should work. Typhoeus already handles http connection pooling

**Comment by topac** [comment]
@vijayanandnandam sure but I would like to not have dependencies on other gems

**Comment by topac** [comment]
this was merged
