### ISSUE TITLE
I need help! How to solve this?

### ISSUE THREAD

**Issue by mateoagudelo** [topac/rmega#39]
Error:
No such file or directory @ rb_file_s_size - C:/xampp/htdocs/descargas/file.rar

My code:
`public_url = 'https://mega.nz/file/TctykRzL#p5xkGEjIz9VcegfbBh2maCD3JGKmsIdaOXahf_ZL-ZI'
 Rmega.download(public_url, Rails.root)`

**Comment by topac** [comment]
Have you tried with other links or another folder other then `Rails.root`?
