### ISSUE TITLE
Be able to upload a folder with its content

### ISSUE THREAD

**Issue by microweb10** [topac/rmega#41]
Thanks for the contribution! 🙏 

Are you planning to add a folder upload functionality? 🤔

**Comment by topac** [comment]
@microweb10 You mean by using the `rmega-up` command line tool?

**Comment by microweb10** [comment]
> @microweb10 You mean by using the `rmega-up` command line tool?

Not really, I mean by using the method `upload` -> https://github.com/topac/rmega#upload

**Comment by topac** [comment]
I don't have time atm to add this feature but it can be implemented with something like:

```ruby
def upload_dir(node, dir)
  Dir['*'].each do |name|
    path = File.join(dir, name)

    if File.directory?(path)
      upload_dir(node.create_folder(name), path)
    elsif File.size(path) > 0
      node.upload(path)
    end
  end
end

upload_dir(storage.root, "/foo/bar")
```
